package com.github.quantakt.anilistclient.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Generated using material theme builder
val md_theme_light_primary = Color(0xFF00658E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC7E7FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E2E)
val md_theme_light_secondary = Color(0xFF933C8B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD7F4)
val md_theme_light_onSecondaryContainer = Color(0xFF380037)
val md_theme_light_tertiary = Color(0xFF236D00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF9DF974)
val md_theme_light_onTertiaryContainer = Color(0xFF062100)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_outline = Color(0xFF71787E)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1F3)
val md_theme_light_inverseSurface = Color(0xFF2E3133)
val md_theme_light_inversePrimary = Color(0xFF84CFFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00658E)

val md_theme_dark_primary = Color(0xFF84CFFF)
val md_theme_dark_onPrimary = Color(0xFF00344C)
val md_theme_dark_primaryContainer = Color(0xFF004C6C)
val md_theme_dark_onPrimaryContainer = Color(0xFFC7E7FF)
val md_theme_dark_secondary = Color(0xFFFFABF0)
val md_theme_dark_onSecondary = Color(0xFF5B0258)
val md_theme_dark_secondaryContainer = Color(0xFF772271)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD7F4)
val md_theme_dark_tertiary = Color(0xFF82DC5B)
val md_theme_dark_onTertiary = Color(0xFF0E3900)
val md_theme_dark_tertiaryContainer = Color(0xFF195200)
val md_theme_dark_onTertiaryContainer = Color(0xFF9DF974)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val md_theme_dark_outline = Color(0xFF8B9198)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val md_theme_dark_inversePrimary = Color(0xFF00658E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF84CFFF)

// Overrides
val light_background = Color(237, 241, 245)
val light_onBackground = Color(92, 114, 138)
val light_surface = Color(250, 250, 250)
val light_onSurface = Color(92, 114, 138)

val dark_background = Color(11,22,34)
val dark_onBackground = Color(159, 173, 189)
val dark_surface = Color(21, 34, 50)
val dark_onSurface = Color(211, 213, 243)
